baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site Theme'

[params]
  description = "Durable and versatile cast iron cookware for every kitchen."
  og_image = "/images/og-image.jpg"
  showNavMenu = false
  
  contact_address1 = "The Hub Nobel Way"
  contact_address2 = "Birmingham, United Kingdom"
  contact_postcode = "B6 7EU"
  contact_phone = "+44 (0) 121 604 6000"
  
  affiliateDisclosure = "This is a fan website and is not endorsed by or affiliated with MasterClass Premium Cookware. The address above is the official headquarters of MasterClass Premium Cookware."

[[params.footerColumns]]
  title = "Shop"
  links = [
    {name = "Skillets", url = "/products/skillets"},
    {name = "Dutch Ovens", url = "/products/dutch-ovens"}
  ]

[[params.footerColumns]]
  title = "About"
  links = [
    {name = "Our Story", url = "/about"},
    {name = "Blog", url = "/blog"}
  ]

[[params.footerColumns]]
  title = "Support"
  links = [
    {name = "FAQs", url = "/faqs"},
    {name = "Contact", url = "/contact"}
  ]

[[params.socialLinks]]
  name = "Facebook"
  url = "https://facebook.com/yourcompany"

[[params.socialLinks]]
  name = "Instagram"
  url = "https://instagram.com/yourcompany"

[[params.socialLinks]]
  name = "Twitter"
  url = "https://twitter.com/yourcompany"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  
[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"