baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site Theme'

[params]
  description = "Durable and versatile cast iron cookware for every kitchen."
  og_image = "/images/og-image.jpg"
  showNavMenu = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
