baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site Theme'

[params]
  description = "Durable and versatile cast iron cookware for every kitchen."
  og_image = "/images/og-image.jpg"
  showNavMenu = true
  footerColumns = [
    {title = "Shop", links = [{name = "Skillets", url = "/products/skillets"}, {name = "Dutch Ovens", url = "/products/dutch-ovens"}]},
    {title = "About", links = [{name = "Our Story", url = "/about"}, {name = "Blog", url = "/blog"}]},
    {title = "Support", links = [{name = "FAQs", url = "/faqs"}, {name = "Contact", url = "/contact"}]}
  ]
  socialLinks = [
    {name = "Facebook", url = "https://facebook.com/yourcompany"},
    {name = "Instagram", url = "https://instagram.com/yourcompany"},
    {name = "Twitter", url = "https://twitter.com/yourcompany"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 3
  

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
